name: Build & Deploy Connect Panel to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare docs and copy Assets (if present)
        run: |
          set -e
          mkdir -p docs
          if [ -d "Assets" ]; then
            rm -rf docs/Assets || true
            cp -R Assets docs/Assets
            echo "Copied Assets -> docs/Assets"
          else
            echo "No repo-root Assets/ directory found; ensure Assets are present under docs/ or update paths."
          fi

      - name: Create docs/index.html (your block unchanged)
        run: |
          cat > docs/index.html <<'HTML'
  <!doctype html>
  <html lang="en">
  <head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Connect With Me</title>
  <meta name="robots" content="index,follow"/>
  <style>
  html,body{margin:0;padding:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,"Helvetica Neue",Arial;}
  main{padding:18px;display:flex;justify-content:center;}
  </style>
  </head>
  <body>
  <main>
<!-- START: original block (unchanged) -->
  <details>
  <summary style="cursor:pointer; display:flex; justify-content:center; align-items:center; list-style:none; padding:66px 0;">
  <img src="Assets/connect.svg?v=4" alt="Connect With Me" width="310" style="display:block;"/>
  </summary>
  <style>
  /* Container */
  .connect-wrap {
max-width: 920px;
margin: 18px auto;
padding: 12px;
box-sizing: border-box;
}
  /* profile views row */
  .profile-views {
  display:flex;
  justify-content:flex-start;
  gap:12px;
  align-items:center;
margin: 10px 0 18px 0;
}
/* Link grid: 3 columns, responsive */
  .links-grid {
  display:flex;
gap: 36px;
  justify-content:center;
  align-items:flex-start;
  flex-wrap:wrap;
}
  /* Column */
  .link-column {
  display:flex;
  flex-direction:column;
gap: 18px;
  align-items:center;
flex: 1 1 160px; /* grow/shrink for even columns */
max-width: 220px;
min-width: 140px;
}
  /* Individual link card (clean / no borders) */
  .link-card {
  display:flex;
  flex-direction:column;
  align-items:center;
  text-decoration:none;
  color:inherit;
  gap:10px;
  transition:transform .12s ease, opacity .12s ease;
}
  .link-card img {
  width:48px;
  height:48px;
  display:block;
}
.link-card:hover { transform: translateY(-4px); opacity: .95; }
  /* Small caption under icons (optional) */
  .link-label {
  font-size:12px;
  color:#4b5563;
  margin-top:4px;
  font-family:system-ui,-apple-system,Segoe UI,Roboto,"Helvetica Neue",Arial;
}
  /* Responsive */
  @media (max-width:740px) {
  .links-grid { gap:22px; }
.link-column { min-width:120px; gap:14px; max-width: 33%; }
}
  </style>
  <div class="connect-wrap" role="region" aria-label="Connect links">
  <div class="profile-views" aria-hidden="false">
  <img
  src="https://komarev.com/ghpvc/?username=Someshdiwan&label=Profile%20views&color=0e75b6&style=flat"
  alt="Profile views counter" style="height:22px;">
  </div>
  <div class="links-grid">
  <!-- LEFT COLUMN -->
  <div class="link-column" aria-label="Left links">
  <a class="link-card" href="https://www.codechef.com/users/someshdiwan7" target="_blank" rel="noopener noreferrer" title="CodeChef — someshdiwan7">
  <img src="https://img.icons8.com/color/96/codechef.png"
  alt="CodeChef logo"
  width="108" height="88"
  style="display:block;" />
  </a>
  <a class="link-card" href="https://huggingface.co/CodeWithSomesh" target="_blank" rel="noopener" title="Hugging Face">
  <img src="https://huggingface.co/front/assets/huggingface_logo-noborder.svg" alt="Hugging Face logo">
  </a>
  <a class="link-card" href="https://www.duolingo.com/profile/Somesh99?via=share_profile_link" target="_blank" rel="noopener noreferrer" title="Duolingo — Somesh99">
  <img src="https://img.icons8.com/color/96/duolingo-logo.png"
  alt="Duolingo logo"
  width="48" height="48"
  style="display:block;" />
  </a>
  </div>
  <!-- MIDDLE COLUMN (new) -->
  <div class="link-column" aria-label="Middle links">
  <!-- Anki — Vocabulary Vault (search results) -->
  <a class="link-card"
  href="https://ankiweb.net/shared/decks?search=Vocabulary%20Vault%20%E2%80%94%20Rich%20English%20vocab%20flashcards"
  target="_blank"
  rel="noopener noreferrer"
  title="Anki — Vocabulary Vault (Search results)"
  aria-label="Open Anki Vocabulary Vault search results">
  <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/anki.svg"
  alt="Anki — Vocabulary Vault"
  width="48" height="48" loading="lazy" style="display:block;" />
  <!-- optional label shown under the icon -->
  <!-- <div class="link-label">Anki — Vocabulary Vault</div> -->
  </a>
  <a class="link-card" href="https://www.producthunt.com/@someshdiwan" target="_blank" rel="noopener" title="Product Hunt">
  <img src="https://cdn.simpleicons.org/producthunt/DA552F" alt="Product Hunt logo">
  </a>
  <a class="link-card" href="https://wakatime.com/@SomeshDiwan" target="_blank" rel="noopener" title="WakaTime">
  <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/wakatime.svg" alt="WakaTime logo">
  </a>
  </div>
  <!-- RIGHT COLUMN -->
  <div class="link-column" aria-label="Right links">
  <a class="link-card" href="https://leetcode.com/u/someshdiwan/" target="_blank" rel="noopener" title="LeetCode">
  <img src="https://img.icons8.com/?size=100&id=wDGo581Ea5Nf&format=png&color=000000" alt="LeetCode logo">
  </a>
  <a class="link-card" href="https://medium.com/@SomeshDiwan" target="_blank" rel="noopener" title="Medium">
  <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/medium.svg" alt="Medium logo">
  </a>
  <a class="link-card" href="https://www.notion.com/@someshdiwan" target="_blank" rel="noopener" title="Notion - Vocabulary Vault">
  <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/notion.svg" alt="Notion logo">
  </a>
  </div>
  </div>
  </div>
  </details>
<!-- END: original block -->
  </main>
  </body>
  </html>
  HTML

- name: Configure Pages (setup target branch)
  uses: actions/configure-pages@v3

- name: Upload artifact for GitHub Pages
  uses: actions/upload-pages-artifact@v1
  with:
    path: ./docs

- name: Deploy to GitHub Pages
  uses: actions/deploy-pages@v1
