name: Generate Monthly Contribution SVG

on:
  schedule:
    # run on 15th (UTC 03:00)
    - cron: '0 3 15 * *'
    # run on days 28-31 then validate last day inside the job
    - cron: '0 3 28-31 * *'
  workflow_dispatch:

concurrency:
  group: generate-monthly-contrib
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm install

      - name: Validate PH_TOKEN presence (debug)
        env:
          PH_TOKEN: ${{ secrets.PH_TOKEN }}
        run: |
          if [ -z "${PH_TOKEN}" ]; then
            echo "PH_TOKEN secret is not set!"
            exit 2
          fi
          echo "PH_TOKEN present (masked)."

      - name: Check schedule -- proceed only on 15 or last day (skip for manual)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          # GitHub runner uses UTC. Adjust if you want local timezone checks.
          TODAY=$(date -u +%d)
          MONTH=$(date -u +%m)
          YEAR=$(date -u +%Y)
          echo "UTC date: ${YEAR}-${MONTH}-${TODAY}"
          # If it's the 15th we proceed
          if [ "$TODAY" = "15" ]; then
            echo "It's the 15th — proceeding."
            exit 0
          fi
          # If day is 28-31, check if it's the last day of the month
          if [ "$TODAY" -ge 28 ]; then
            # compute tomorrow's day; if tomorrow day is 01 => today is last day
            TOMORROW=$(date -u -d "tomorrow" +%d)
            if [ "$TOMORROW" = "01" ]; then
              echo "Today is last day of month — proceeding."
              exit 0
            else
              echo "Not last day (today ${TODAY}). Exiting."
              exit 0   # we exit 0 to treat this as a no-op scheduled run
            fi
          fi
          echo "Not a scheduled run target day (not 15 or last day). Exiting."
          exit 0

      - name: Generate monthly contribution SVG (monthly line)
        env:
          PH_TOKEN: ${{ secrets.PH_TOKEN }}
          GH_TOKEN: ${{ secrets.PH_TOKEN }}   # map into GH_TOKEN in case scripts expect it
        run: |
          mkdir -p Assets
          node scripts/generate_monthly_line.js --user Someshdiwan --year $(date +%Y) --out Assets/contrib-monthly-line.svg

      - name: Sanity output (debug)
        run: |
          echo "Listing Assets folder:"
          ls -la Assets || true
          echo "Head of generated SVG (first 20 lines):"
          head -n 20 Assets/contrib-monthly-line.svg || true

      - name: Commit & push if changed (safe)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin "$BRANCH"
          git add Assets/contrib-monthly-line.svg || true

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update monthly contribution svg (auto)" || true

          if git push origin "HEAD:$BRANCH"; then
            echo "✅ Pushed successfully"
            exit 0
          fi

          echo "Push failed — attempting rebase/merge retry..."
          git fetch origin "$BRANCH"
          git rebase "origin/$BRANCH" || (git rebase --abort || true && git merge --no-edit "origin/$BRANCH")
          git add Assets/contrib-monthly-line.svg || true
          git commit -m "chore: update monthly contribution svg (auto, post-rebase)" || true
          git push origin "HEAD:$BRANCH" || (echo "❌ Final push attempt failed" && exit 1)