name: Generate Monthly Contribution SVG

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm install

      - name: Generate monthly contribution SVG
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node scripts/generate_monthly_graph.js --user Someshdiwan --year $(date +%Y) --out ./assets/contrib-monthly.svg

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/contrib-monthly.svg || true
          if git diff --staged --quiet; then
            echo "No change"
            exit 0
          fi
          git commit -m "chore: update monthly contribution svg"
          git push origin HEAD:main