name: Auto increment profile likes

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

env:
  SCRIPT_PATH: .github/workflows/scripts/fetch_views.py
  OUTPUT_PATH: .github/profile-views.json
  SVG_PATH: .github/profile-views.svg
  LIKE_ISSUE_NUMBER: '1'  # 👈 replace this with the issue number you’ll use for likes

jobs:
  add-like:
    runs-on: ubuntu-latest
    if: github.event.issue.number == env.LIKE_ISSUE_NUMBER
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: python -m pip install --upgrade pip requests

      - name: Increment like if comment contains +1 or ❤️
        if: contains(github.event.comment.body, '+1') || contains(github.event.comment.body, '❤️') || contains(github.event.comment.body, '❤')
        run: |
          python "$SCRIPT_PATH" --inc-like --output "$OUTPUT_PATH" --svg "$SVG_PATH"

      - name: Commit and push changes
        if: contains(github.event.comment.body, '+1') || contains(github.event.comment.body, '❤️') || contains(github.event.comment.body, '❤')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUTPUT_PATH" "$SVG_PATH" || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "❤️ auto-like increment from issue comment"
          git push