name: Increment profile like (manual)

on:
  workflow_dispatch:
    inputs: {}

permissions:
  contents: write

jobs:
  inc-like:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: python .github/workflows/scripts/fetch_views.py --inc-like --output .github/profile-views.json --svg .github/profile-views.svg

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/profile-views.json .github/profile-views.svg
          git commit -m "chore: increment profile like (manual)"
          git push