name: Increment profile like from Issue comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

env:
  SCRIPT_PATH: .github/workflows/scripts/fetch_views.py
  OUTPUT_PATH: .github/profile-views.json
  SVG_PATH: .github/profile-views.svg
  LIKE_ISSUE_NUMBER: '1'    # <-- set to the issue number you will use for likes

jobs:
  maybe-inc-like:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event info
        run: |
          echo "Event issue: ${{ github.event.issue.number }}"
          echo "Comment body: <<${{ github.event.comment.body }}>>"

      - name: Check comment & run script if like
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = Number(process.env.LIKE_ISSUE_NUMBER || 0);
            const eventIssue = context.payload.issue && context.payload.issue.number;
            const body = (context.payload.comment && context.payload.comment.body || "").trim();

            if (!eventIssue || eventIssue !== issueNumber) {
              core.info(`Comment not on like-issue (wanted ${issueNumber}, got ${eventIssue}). Exiting.`);
              return;
            }

            // Accept patterns "+1" or heart emoji anywhere
            const isLike = /^\+1\s*$/.test(body) || body.includes("❤️") || body.includes("❤");
            if (!isLike) {
              core.info("Comment doesn't look like a like. Exiting.");
              return;
            }

            core.info("Detected like comment — returning RUN flag");
            return "RUN";

      - name: Run inc-like if flagged
        if: steps.maybe-inc-like.outputs.result == 'RUN' || steps.maybe-inc-like.outputs.result == '\"RUN\"'
        run: |
          # Checkout full history for safe push
          git --version || true
          git config --global --add safe.directory /github/workspace
          git fetch --all
          # install python deps
          python -m pip install --upgrade pip requests
          # run the script to increment likes
          python "$SCRIPT_PATH" --inc-like --output "$OUTPUT_PATH" --svg "$SVG_PATH"

      - name: Commit & push increment (safe)
        if: steps.maybe-inc-like.outputs.result == 'RUN' || steps.maybe-inc-like.outputs.result == '\"RUN\"'
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          # checkout properly (actions/checkout not used so we don't double checkout)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$OUTPUT_PATH" "$SVG_PATH" README.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: increment profile like (auto from issue comment)" || true
          # push with rebase fallback
          if git push origin "HEAD:$BRANCH"; then
            echo "Pushed successfully"
            exit 0
          fi
          git fetch origin "$BRANCH"
          git rebase "origin/$BRANCH" || (git rebase --abort || true && git merge --no-edit "origin/$BRANCH")
          git add "$OUTPUT_PATH" "$SVG_PATH" README.md || true
          git commit -m "chore: increment profile like (auto, post-rebase)" || true
          git push origin "HEAD:$BRANCH" || (echo "Final push failed" && exit 1)