name: Increment profile like (manual)

concurrency:
  group: profile-like
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs: {}

permissions:
  contents: write

env:
  SCRIPT_PATH: .github/workflows/scripts/fetch_views.py
  OUTPUT_PATH: .github/profile-views.json
  SVG_PATH: .github/profile-views.svg

jobs:
  inc-like:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Run script to increment like
        run: |
          if [ ! -f "$SCRIPT_PATH" ]; then
            echo "Error: script not found at $SCRIPT_PATH"
            exit 2
          fi
          python "$SCRIPT_PATH" --inc-like --output "$OUTPUT_PATH" --svg "$SVG_PATH"

      - name: Commit & push like increment (safe rebase + retry)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin "$BRANCH"

          git add "$OUTPUT_PATH" "$SVG_PATH" README.md || true

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: increment profile like (manual)" || true

          if git push origin "HEAD:$BRANCH"; then
            echo "Pushed successfully"
            exit 0
          fi

          echo "Push failed — attempting rebase on origin/$BRANCH and retry"
          git fetch origin "$BRANCH"
          git rebase "origin/$BRANCH" || (echo "Rebase failed — attempting merge" && git rebase --abort || true && git merge --no-edit "origin/$BRANCH")
          git add "$OUTPUT_PATH" "$SVG_PATH" README.md || true
          git commit -m "chore: increment profile like (manual, post-rebase)" || true
          git push origin "HEAD:$BRANCH" || (echo "Final push attempt failed — aborting" && exit 1)