name: Generate Dark Mode GitHub Contribution Grid Snake Animation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate GitHub contribution grid snake with dark yellow snake color for dark mode
      - name: Generate Dark Mode Contribution Snake Animation (Dark Yellow)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Someshdiwan
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-darkyellow.svg?palette=darkyellow&color_snake=#9B7D33

      # Step 2: Deploy to GitHub Pages (Dark Mode)
      - name: Deploy to GitHub Pages (Dark Mode)
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
