name: Generate GitHub Contribution Grid Snake Animation

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - master  # Runs on push to master branch

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate GitHub contribution grid snake with yellow snake color (black background)
      - name: Generate Contribution Snake Animation (Yellow Snake, Black Background)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Someshdiwan
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFFF00&palette=github-dark  # Yellow snake, black background

      # Step 2: Generate GitHub contribution grid snake with yellow snake color (white background)
      - name: Generate Contribution Snake Animation (Yellow Snake, White Background)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Someshdiwan
          outputs: |
            dist/github-contribution-grid-snake-light.svg?color_snake=%23FFFF00&palette=github-light  # Yellow snake, white background

      # Step 3: Deploy to GitHub Pages (Both Snake Versions)
      - name: Deploy to GitHub Pages (Yellow Snake)
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
