name: GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate Snake
      uses: Platane/snk@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
