name: Generate GitHub Contribution Grid Snake Animation

on:
  # Automatically run the job every 24 hours
  schedule:
    - cron: "0 * * * *"
  
  # Allows manual triggering of the job at any time
  workflow_dispatch:
  
  # Runs on every push to the master branch
  push:
    branches:
      - master

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Step 1: Generate GitHub contribution grid snake with a yellow snake color
      - name: Generate Contribution Snake Animation (Yellow)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Someshdiwan
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-yellow.svg?palette=yellow

      # Step 2: Push the generated snake animation to the output branch for display
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
