name: Generate GitHub Contribution Grid Snake Animation

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - master  # Runs on push to master branch

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate GitHub contribution grid snake with default (original) snake color and dark mode look (black background)
      - name: Generate Contribution Snake Animation (Default Snake Color, Dark Mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Someshdiwan
          outputs: |
            dist/github-contribution-grid-snake-dark-mode.svg?palette=github-dark  # Default snake color (blue), dark background

      # Step 2: Generate GitHub contribution grid snake with default snake color and light mode look (white background)
      - name: Generate Contribution Snake Animation (Default Snake Color, White Background)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Someshdiwan
          outputs: |
            dist/github-contribution-grid-snake-white.svg?palette=github-light  # Default snake color (blue), white background

      # Step 3: Deploy to GitHub Pages (Both Snake Versions)
      - name: Deploy to GitHub Pages (Default Snake Color, Dark Mode)
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
