name: Render WakaTime SVG (nightly)

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

concurrency:
  group: render-waka-svg
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm install

      - name: Render WakaTime SVG
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USERNAME: ${{ secrets.WAKATIME_USERNAME }} # optional
        run: node ./scripts/render_waka_svg.js

      - name: Generate streak.svg (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./scripts/generate_streak.js || echo "streak generator failed"

      - name: Commit assets if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add wakatime.svg streak.svg || true

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update generated assets"

          git fetch origin main
          git stash push --include-untracked -m "gh-actions/pre-pull-stash" || true
          git pull --rebase origin main
          git stash pop || true
          git push origin main
