name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          # Attempt to disable timeline and bar chart output (if supported)
          SHOW_TIMELINE: "False"
          SHOW_BAR_CHART: "False"

      - name: Remove Timeline and Bar Graph Output
        run: |
          echo "Removing timeline and bar graph output from README..."
          # Remove any lines containing 'Timeline'
          sed -i '/Timeline/d' README.md
          # Remove any lines containing the bar graph image URL (adjust the pattern if needed)
          sed -i '/bar_graph.png/d' README.md

      - name: Commit and Push README Update
        run: |
          git config --global user.name "Someshdiwan"
          git config --global user.email "someshdiwan369@gmail.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Updated WakaTime stats without timeline/bar graph"
            git push
          fi
