name: Update WakaTime Stats in README

on:
  schedule:
    - cron: "0 20 * * *"  # Runs daily at 20:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Update README with WakaTime stats
      - name: Update WakaTime Stats in README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update WakaTime stats"
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: "last_30_days"
          SHOW_TIME: "true"

            # 3. Commit and Push changes (force update)
      - name: Commit and Push README Update
        run: |
          git config --global user.name "Someshdiwan"
          git config --global user.email "someshdiwan369@gmail.com"
          echo "Last updated on $(date)" > waka_timestamp.txt
          git add README.md waka_timestamp.txt
          git commit -m "Updated WakaTime stats [$(date)]" || echo "No changes to commit."
          git pull --rebase --autostash origin main || git rebase --skip
          git push

