name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_TIMELINE: "False"
          SHOW_BAR_CHART: "False"

      - name: Remove unwanted sections from README
        run: |
          echo "Removing unwanted sections from README..."
          sed -i '/Not Opted to Hire/d' README.md
          sed -i '/🐱‍💻 Projects:/,/^$/d' README.md
          sed -i '/I Mostly Code in Jupyter Notebook/d' README.md
          sed -i '/^```text/,/^```/d' README.md
          sed -i '/Timeline/d' README.md
          sed -i '/bar_graph\.png/d' README.md
          rm -rf assets  # Remove the assets folder

      - name: Commit and Push README Update
        run: |
          git config --global user.name "Someshdiwan"
          git config --global user.email "someshdiwan369@gmail.com"
          git add README.md
          git rm -r --cached assets  # Ensure assets folder is removed from Git
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Updated WakaTime stats and removed unwanted sections"
            git pull --rebase origin main
            git push
          fi
