name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          # Attempt to disable timeline and bar chart output (if supported)
          SHOW_TIMELINE: "False"
          SHOW_BAR_CHART: "False"

      - name: Remove Unwanted Sections from README
        run: |
          echo "Removing unwanted sections from README..."
          # Remove the "Not Opted to Hire" line
          sed -i '/Not Opted to Hire/d' README.md
          # Remove the block from "🐱‍💻 Projects:" until the first blank line after it
          sed -i '/🐱‍💻 Projects:/,/^$/d' README.md
          # Remove the "**I Mostly Code in Jupyter Notebook**" line
          sed -i '/I Mostly Code in Jupyter Notebook/d' README.md
          # Remove the code block with language stats: from a line starting with "```text" until the closing "```"
          sed -i '/^```text/,/^```/d' README.md
          # Remove the "Timeline" line and any line containing "bar_graph.png"
          sed -i '/Timeline/d' README.md
          sed -i '/bar_graph\.png/d' README.md

      - name: Remove Assets Folder
        run: |
          if [ -d "assets" ]; then
            echo "Removing assets folder..."
            rm -rf assets
            git rm -rf --cached assets || echo "assets folder not tracked"
          else
            echo "No assets folder found."
          fi

      - name: Commit and Push README Update
        run: |
          git config --global user.name "Someshdiwan"
          git config --global user.email "someshdiwan369@gmail.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Updated WakaTime stats and removed unwanted sections"
            git pull --rebase origin main
            git push
          fi
