name: WakaTime Readme

on:
  schedule:
    - cron: "0 20 * * *"  # Runs daily at 20:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Update README with WakaTime stats
      - name: Update WakaTime Stats in README
        uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Update Wakapi stats"
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: "last_30_days"
          SHOW_TIME: "true"

      # 3. Commit and Push changes (if any)
      - name: Commit and Push README Update
        run: |
          git config --global user.name "Someshdiwan"
          git config --global user.email "someshdiwan369@gmail.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Updated WakaTime stats"
            git pull --rebase --autostash origin main || git rebase --skip
            git push
          fi
          
